apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimoni
  labels:
    {{- include "minimoni.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.core.replicaCount }}
  revisionHistoryLimit: {{ .Values.core.replicaCount }}

  selector:
    matchLabels:
      {{- include "minimoni.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minimoni.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.core.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "minimoni.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.core.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.core.securityContext | nindent 12 }}
          image: "{{ .Values.core.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.core.image.pullPolicy }}
          ports:
            - name: ssh
              containerPort: 32200
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 32200
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 32200
            initialDelaySeconds: 10
            periodSeconds: 15
          volumeMounts:
          - mountPath: /minimoni/pickers
            name: minimoni-pickers
          - mountPath: /minimoni/data
            name: minimoni-data
          - mountPath: /minimoni/config
            name: minimoni-cfg
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 10022
            runAsGroup: 10022
            seccompProfile:
              type: 'RuntimeDefault'
      volumes:
        - name: minimoni-pickers
          persistentVolumeClaim:
            claimName: minimoni-pickers-pvc
        - name: minimoni-data
          persistentVolumeClaim:
            claimName: minimoni-data-pvc
        - name: ssh-data
          persistentVolumeClaim:
            claimName: minimoni-ssh-data-pvc
        - name: minimoni-cfg
          configMap:
            defaultMode: 420
            name: minimoni-cfg
      {{- with .Values.core.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.core.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.core.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mm-operator
  labels:
    {{- include "mm-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mm-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mm-operator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.mmoperator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "minimoni.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.mmoperator.podSecurityContext | nindent 8 }}
      containers:
        - name: mm-operator
          securityContext:
            {{- toYaml .Values.mmoperator.securityContext | nindent 12 }}
          image: "{{ .Values.mmoperator.image.repository }}:{{ .Values.mmoperator.image.tag }}"
          imagePullPolicy: {{ .Values.mmoperator.image.pullPolicy }}
          volumeMounts:
          - mountPath: /mm-operator/data
            name: minimoni-data
          resources:
            {{- toYaml .Values.mmoperator.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 10022
            runAsGroup: 10022
            seccompProfile:
              type: 'RuntimeDefault'
      volumes:
       - name: minimoni-data
         persistentVolumeClaim:
           claimName: minimoni-data-pvc
      {{- with .Values.mmoperator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.mmoperator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.mmoperator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
