{{- if .Values.mmoperator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minimoni.serviceAccountName" . }}
  labels:
    {{- include "minimoni.labels" . | nindent 4 }}
  {{- with .Values.mmoperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "monitoring"
  name: {{ include "minimoni.serviceAccountName" . }}-role-namespaced
rules:
  - apiGroups: [""]
    resources: [services]
    verbs: [get, create, apply, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "monitoring"
  name: {{ include "minimoni.serviceAccountName" . }}-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "minimoni.serviceAccountName" . }}-role-namespaced
subjects:
  - kind: ServiceAccount
    name: {{ include "minimoni.serviceAccountName" . }}
{{- end -}}