core:  
  image:
    pullPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: k3s-node-fast-1
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "fast"
    effect: "NoSchedule"
mmoperator: 
  image:
    pullPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: k3s-node-fast-1
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "fast"
    effect: "NoSchedule"
  
