# Default values for minimoni.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
core:  
  replicaCount: 1
  
  image:
    repository: docker.k8s.dom.cz0.cz/minimoni
    pullPolicy: IfNotPresent
      
  appSettings:
    network:
        host: k8s.dom.cz0.cz
        sshPort: 32200
        tunnelsStartPort: 32201
    influxdb:
        connectionUrl: https://influxdb2.k8s.dom.cz0.cz
        dbToken: sPlu6VKZ0sWYf6MnJ0QqVgUjPEzaq5tw
    management:
        logLevel: info
        clientRegistrationTokenTTL: 15m
        initialSetupCompleted: true
        propagateAdminKeys: true
        admin_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM0spf+FDXkAHd5V6yKW8oABXydz+vOsQlPjmOcC6Zfg

      
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  
  podSecurityContext: {}
    # fsGroup: 2000
  
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  
  service:
    type: NodePort
    port: 32200
  
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  
  nodeSelector: {}
  
  tolerations: []
  
  affinity: {}
  
mmoperator: 
  image:
    repository: docker.k8s.dom.cz0.cz/mm-operator
    tag: 0.1.4

    pullPolicy: IfNotPresent
  
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name:
  
  podSecurityContext: {}
    # fsGroup: 2000
  
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  
  nodeSelector: {}
  
  tolerations: []
  
  affinity: {}
  