name: Pull Request Validator
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
#  chart-lint:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # tag=v3.5.3
#
#      - name: Set up Helm
#        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # tag=v3.5
#        with:
#          version: 'v3.12.0'
#
#      - name: Run Validator Script
#        run: ./.scripts/validators/lint.sh

  chart-sec-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # tag=v3.5.3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # tag=v3.5
        with:
          version: 'v3.12.0'

      - name: Set up python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # tag=v4.6.1
        with:
          python-version: 3.7

      ## Requires GitHub Advanced Security license for use in private repositories.
      #- name: Run Trivy for GitHub Security Tab
      #  uses: aquasecurity/trivy-action@41f05d9ecffa2ed3f1580af306000f734b733e54 # tag=0.11.2
      #  with:
      #    scan-type: 'config'
      #    hide-progress: false
      #    format: 'sarif'
      #    scan-ref: 'charts'
      #    output: 'trivy-results.sarif'
      #    ignore-unfixed: true

      #- name: Upload Trivy scan results to GitHub Security tab
      #  uses: github/codeql-action/upload-sarif@312e093a1892bd801f026f1090904ee8e460b9b6 # v2.1.34
      #  with:
      #    sarif_file: 'trivy-results.sarif'

      - name: Run Validator Script
        run: 'pwd && ls -al && find charts'

      - name: Run Trivy for pipeline result
        uses: aquasecurity/trivy-action@41f05d9ecffa2ed3f1580af306000f734b733e54 # tag=0.11.2
        with:
          scan-type: 'config'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          hide-progress: false
          format: 'table'
          scan-ref: 'charts'
          exit-code: '1'
          ignore-unfixed: true
